### ISSUE TITLE
Templates para subir para PROD 

### ISSUE THREAD

**Issue by GutoMFreitas** [toolzzlabzz/toolzz-bots#307]
Template pré-kickoff inteligente
[toolzz-export-pr-kickoff-inteligente-ai4cc70.json](https://github.com/user-attachments/files/17258579/toolzz-export-pr-kickoff-inteligente-ai4cc70.json)

Template Teste Vocacional 
[toolzz-export-teste-vocacional-wevvtyt.json](https://github.com/user-attachments/files/17258582/toolzz-export-teste-vocacional-wevvtyt.json)

**Comment by GutoMFreitas** [comment]
Categoria “Atendimento e Suporte”
1.😍 Suporte ao cliente (atualização)
2.📱 Integração com Toolzz Chat (novo item)
3.🧠 Pré-Kickoff Inteligente (novo item)
4.💡 IA de atendimento (novo item)

Categoria “Educação”
5.📝 Teste vocacional (novo item)

**Comment by GutoMFreitas** [comment]
Categoria “Atendimento e Suporte”
1.😍 Suporte ao cliente (atualização)
[toolzz-export-suporte-ao-cliente-wt8hs90.json](https://github.com/user-attachments/files/17261387/toolzz-export-suporte-ao-cliente-wt8hs90.json)

2.📱 Integração com Toolzz Chat (novo item)
[toolzz-export-integra-o-com-toolzz-chat-eb3ndbk.json](https://github.com/user-attachments/files/17261404/toolzz-export-integra-o-com-toolzz-chat-eb3ndbk.json)

3.🧠 Pré-Kickoff Inteligente (novo item)
[toolzz-export-pr-kickoff-inteligente-ai4cc70.json](https://github.com/user-attachments/files/17258579/toolzz-export-pr-kickoff-inteligente-ai4cc70.json)

4.💡 IA de atendimento (novo item)
[toolzz-export-ia-de-atendimento-0y0qt7v (1).json](https://github.com/user-attachments/files/17261426/toolzz-export-ia-de-atendimento-0y0qt7v.1.json)

Categoria Educação
5.📝 Teste vocacional (novo item)
[toolzz-export-teste-vocacional-wevvtyt.json](https://github.com/user-attachments/files/17258582/toolzz-export-teste-vocacional-wevvtyt.json)

**Comment by kweripx** [comment]
#308
